name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    container: python:3.7-buster

    services:
      postgres:
        image: postgres:9
        env:
          POSTGRES_USER: lemur
          POSTGRES_PASSWORD: lemur
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      TOXENV: py37
      PIP_DOWNLOAD_CACHE: .pip_download_cache
      # The following line is a temporary workaround for this issue: https://github.com/pypa/setuptools/issues/2230
      SETUPTOOLS_USE_DISTUTILS: stdlib
      # do not load /etc/boto.cfg with Python 3 incompatible plugin
      # https://github.com/travis-ci/travis-ci/issues/5246#issuecomment-166460882
      BOTO_CONFIG: /doesnotexist

    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js 8.x
      uses: actions/setup-node@v1
      with:
        node-version: 8.x
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest