name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    container: python:3.7-buster

    services:
      postgres:
        image: postgres:9
        env:
          POSTGRES_USER: lemur
          POSTGRES_PASSWORD: lemur
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      TOXENV: py37
      PIP_DOWNLOAD_CACHE: .pip_download_cache
      # The following line is a temporary workaround for this issue: https://github.com/pypa/setuptools/issues/2230
      SETUPTOOLS_USE_DISTUTILS: stdlib
      # do not load /etc/boto.cfg with Python 3 incompatible plugin
      # https://github.com/travis-ci/travis-ci/issues/5246#issuecomment-166460882
      BOTO_CONFIG: /doesnotexist

    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js 8.x
      uses: actions/setup-node@v1
      with:
        node-version: 8.x
    - name: Install Bower
      run: npm install -g bower
    - name: Upgrade setuptools
      run: pip install --upgrade setuptools
    - run: pip install coveralls bandit
    - run: make test
    - run: bandit -r . -ll -ii -x lemur/tests/,docs
    - run: coveralls
